#!/bin/bash

if [ "`id -ru`" != "0" ];then
    echo "ERROR: Please use sudo."
    exit 1
fi

. bashlib_y

#__ask_yes_no_color_caption=red
#__ask_yes_no_color_yn=yellow

#echo -n "Uninstall current ruby and install new ruby."
if ask_yes_no "Uninstall current ruby and install new ruby.";then
    echo uninstalling.
    rpm -qa | grep ruby
    # rpm -e `rpm -qa | grep ruby`
    # rm -rf `find /usr -type d -name gems`
fi
