#!/bin/bash

# 対象ディレクトリ
DIR="$1" # /var/lib/dshared/rpmbuilds
LINK_DIR="/var/lib/dshared/files/by_sha256"
function digdir(){
   while [ $# -gt 0 ]; do
      mkdir -p "$1"
      chmod 775 "$1"
      chown dshared:dshared "$1"
      shift
   done
}

# ディレクトリを再帰的にたどる

find "$DIR" -type d -not -type l | while read -r subdir; do
    echo "Processing directory: $subdir"
    for file in "$subdir"/*; do
        if test -f "$file" && ! test -L "$file"; then
            # チェックサムを計算
            checksum=$(sha256sum "$file" | awk '{ print $1 }')
            # ハードリンクのパスを設定
            link_d_each="$LINK_DIR/${checksum:0:1}/${checksum:1:1}"
	        link_path="$link_d_each/$checksum"
	        digdir "$LINK_DIR" "$LINK_DIR/${checksum:0:1}" "$link_d_each"
            # 既存のハードリンクチェック
            if [ ! -e "$link_path" ]; then
	            ls -lad $link_d_each
                # ハードリンクを作成
                ln "$file" "$link_path"
		        chmod a-w,a+r "$file"
                chown dshared:dshared "$link_path" 
                echo "Created hard link for $file with checksum $checksum"
            else
                echo "Link already exists for checksum $checksum, link back to $file"
		        if ! rm -f $file; then
		            echo "cannot remove $file"
		        else
                    ln "$link_path" "$file"
		        fi
            fi
        fi
    done    
done

find "$LINK_DIR" -type d -not -type l | while read -r subdir; do
    for file in "$subdir"/*; do
        if test -f "$file" && ! test -L "$file"; then
            # リンクカウントを取得
            LINK_COUNT=$(ls -l "$file" | awk '{print $2}')
            # リンクカウントが1の場合に削除
            if [ "$LINK_COUNT" -eq 1 ]; then
                sudo rm -f "$file"
            fi
	    fi
    done
    rmdir $subdir 2> /dev/null
done
